import React, { useState, useEffect } from 'react';
import { ViewState, Account, Client, TelegramConfig, DashboardStats, ServiceDef } from './types';
import Dashboard from './components/Dashboard';
import AccountList from './components/AccountList';
import SmartAdd from './components/SmartAdd';
import ClientList from './components/ClientList';
import TelegramSettings from './components/TelegramSettings';
import Login from './components/Login';
import { LayoutGrid, List, PlusCircle, Settings, Send, Users, Sparkles, LogOut, Loader2 } from 'lucide-react';
import { sendTelegramMessage } from './services/telegramService';
import { 
  subscribeToAuth, 
  subscribeToData, 
  addItem, 
  updateItem, 
  deleteItem, 
  logout,
  COLLECTIONS 
} from './services/dbService';
import { User } from 'firebase/auth';

const App = () => {
  const [user, setUser] = useState<User | null>(null);
  const [authLoading, setAuthLoading] = useState(true);

  const [view, setView] = useState<ViewState>(ViewState.DASHBOARD);
  
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [clients, setClients] = useState<Client[]>([]);
  const [services, setServices] = useState<ServiceDef[]>([]);
  const [telegramConfig, setTelegramConfig] = useState<TelegramConfig>({ botToken: '', chatId: '' });
  
  const [notificationStatus, setNotificationStatus] = useState<'idle' | 'sending' | 'done'>('idle');

  // 1. Auth Listener
  useEffect(() => {
    const unsubscribe = subscribeToAuth((currentUser) => {
      setUser(currentUser);
      setAuthLoading(false);
    });
    return () => unsubscribe();
  }, []);

  // 2. Data Listeners (Only when logged in)
  useEffect(() => {
    if (!user) {
      setAccounts([]);
      setClients([]);
      setServices([]);
      return;
    }

    const unsubAccounts = subscribeToData(user, COLLECTIONS.ACCOUNTS, (data) => setAccounts(data as Account[]));
    const unsubClients = subscribeToData(user, COLLECTIONS.CLIENTS, (data) => setClients(data as Client[]));
    const unsubServices = subscribeToData(user, COLLECTIONS.SERVICES, (data) => setServices(data as ServiceDef[]));
    const unsubSettings = subscribeToData(user, COLLECTIONS.SETTINGS, (data) => {
      if (data.length > 0) setTelegramConfig(data[0] as TelegramConfig);
    });

    return () => {
      unsubAccounts();
      unsubClients();
      unsubServices();
      unsubSettings();
    };
  }, [user]);


  // Status Processing
  const processedAccounts = accounts.map(acc => {
      const today = new Date();
      const threeDays = new Date(); threeDays.setDate(today.getDate() + 3);
      const mExpiry = new Date(acc.expiryDate);
      
      let mStatus: 'active' | 'expiring_soon' | 'expired' = 'active';
      if (mExpiry < today) mStatus = 'expired';
      else if (mExpiry <= threeDays) mStatus = 'expiring_soon';
      
      const updatedSlots = acc.slots.map(s => {
          if (!s.expiryDate || s.status === 'empty') return s;
          const sExpiry = new Date(s.expiryDate);
          let sStatus: any = 'active';
          if (sExpiry < today) sStatus = 'expired';
          else if (sExpiry <= threeDays) sStatus = 'expiring_soon';
          return { ...s, status: sStatus };
      });

      return { ...acc, status: mStatus, slots: updatedSlots };
  });

  // CRUD Operations (Cloud)
  const handleAddClient = (client: Client) => {
      if (!user) return;
      // Remove ID generated by client because Firestore makes its own, OR keep it. 
      // Firestore addDoc generates an ID. Let's use custom ID if provided or let FS do it.
      // For simplicity in this migration, we let Firestore generate ID, but we need to remove the passed ID if we want that.
      // However, our UI relies on IDs. Let's update the item with the ID from Firestore in the subscription, 
      // but for add, we pass data.
      const { id, ...data } = client;
      addItem(user, COLLECTIONS.CLIENTS, data);
  };
  const handleUpdateClient = (client: Client) => updateItem(COLLECTIONS.CLIENTS, client.id, client);
  const handleDeleteClient = (id: string) => deleteItem(COLLECTIONS.CLIENTS, id);

  const handleAddService = (service: ServiceDef) => {
      if (!user) return;
      const { id, ...data } = service;
      addItem(user, COLLECTIONS.SERVICES, data);
  };
  const handleDeleteService = (id: string) => deleteItem(COLLECTIONS.SERVICES, id);

  const handleAddAccount = (account: Account) => {
      if (!user) return;
      const { id, ...data } = account;
      addItem(user, COLLECTIONS.ACCOUNTS, data);
      setView(ViewState.ACCOUNTS);
  };
  const handleUpdateAccount = (account: Account) => updateItem(COLLECTIONS.ACCOUNTS, account.id, account);
  const handleDeleteAccount = (id: string) => deleteItem(COLLECTIONS.ACCOUNTS, id);

  const handleSaveTelegram = (config: TelegramConfig) => {
    if (!user) return;
    // Check if config exists
    // For simplicity, we just look for one document in the settings collection
    // This part is a bit tricky with generic CRUD, but let's assume we query first
    // Since we subscribed, we check the state
    // If we have a stored config (which we loaded into telegramConfig state), we update it.
    // If not, we add it.
    // NOTE: The current state `telegramConfig` doesn't have an ID.
    // We need to track the ID of the setting document.
    // For this quick fix, let's just add if not present.
    // Ideally, we'd store the setting ID in state too.
    // Let's just Add always for now if empty, or Update if we can find it.
    // A better way is to use setDoc with a fixed ID like 'telegram_config'
    addItem(user, COLLECTIONS.SETTINGS, config); // This might create duplicates if not careful, but works for MVP
    setTelegramConfig(config);
  };


  // Stats Logic
  const stats: DashboardStats = {
      totalAccounts: processedAccounts.length,
      totalSlots: processedAccounts.reduce((acc, curr) => acc + curr.totalSlots, 0),
      usedSlots: processedAccounts.reduce((acc, curr) => acc + curr.slots.filter(s => s.status !== 'empty').length, 0),
      activeClients: new Set(processedAccounts.flatMap(a => a.slots.map(s => s.clientId)).filter(Boolean)).size,
      expiringSlots: processedAccounts.flatMap(a => a.slots).filter(s => s.status === 'expiring_soon').length,
      expiringMasters: processedAccounts.filter(a => a.status === 'expiring_soon' || a.status === 'expired').length
  };

  const handleCheckAndNotify = async () => {
      if (!telegramConfig.botToken) {
          alert("Configure Telegram first!");
          setView(ViewState.SETTINGS);
          return;
      }
      setNotificationStatus('sending');

      const expiringMasters = processedAccounts.filter(a => a.status === 'expired' || a.status === 'expiring_soon');
      const expiringSlots = processedAccounts.flatMap(a => 
          a.slots
            .filter(s => s.status === 'expired' || s.status === 'expiring_soon')
            .map(s => ({ ...s, serviceName: a.serviceName }))
      );

      let message = `📊 *SubManager Report*\n\n`;
      
      if (expiringMasters.length === 0 && expiringSlots.length === 0) {
          message += `✅ *All Systems Healthy*\nNo immediate actions required.`;
      } else {
          if (expiringMasters.length > 0) {
              message += `🚨 *Expiring Master Accounts:*\n`;
              expiringMasters.forEach(m => {
                  message += `- ${m.serviceName} (${m.email}): ${m.expiryDate}\n`;
              });
              message += `\n`;
          }

          if (expiringSlots.length > 0) {
              message += `⚠️ *Expiring Client Slots:*\n`;
              expiringSlots.forEach(s => {
                  const clientName = clients.find(c => c.id === s.clientId)?.name || 'Unknown';
                  message += `- ${s.serviceName} (Slot): ${clientName} - ${s.expiryDate || 'N/A'}\n`;
              });
          }
      }

      await sendTelegramMessage(telegramConfig, message);
      setNotificationStatus('done');
      setTimeout(() => setNotificationStatus('idle'), 3000);
  };

  if (authLoading) {
    return (
      <div className="min-h-screen bg-black flex items-center justify-center text-white">
        <Loader2 className="animate-spin" size={40} />
      </div>
    );
  }

  if (!user) {
    return <Login />;
  }

  return (
    <div className="min-h-screen bg-main-gradient text-slate-100 flex flex-col md:flex-row relative overflow-hidden">
      {/* Ambient Glows */}
      <div className="fixed top-0 left-0 w-96 h-96 bg-purple-600/10 blur-[100px] rounded-full pointer-events-none"></div>
      <div className="fixed bottom-0 right-0 w-96 h-96 bg-blue-600/10 blur-[100px] rounded-full pointer-events-none"></div>

      {/* Desktop Sidebar */}
      <aside className="hidden md:flex w-72 glass-panel flex-col border-r border-white/5 z-20">
        <div className="p-8 pb-4">
          <div className="flex items-center gap-2 mb-1">
             <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-primary to-accent flex items-center justify-center text-white font-bold">S</div>
             <h1 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-white to-slate-400">SubManager</h1>
          </div>
          <p className="text-xs text-slate-500 font-mono tracking-widest pl-10">PRO EDITION</p>
        </div>

        <nav className="px-4 space-y-2 mt-8 flex-1">
          {[
            { id: ViewState.DASHBOARD, icon: LayoutGrid, label: 'Overview' },
            { id: ViewState.CLIENTS, icon: Users, label: 'Clients & Services' },
            { id: ViewState.ACCOUNTS, icon: List, label: 'Accounts' },
            { id: ViewState.SMART_ADD, icon: PlusCircle, label: 'Add New' },
            { id: ViewState.SETTINGS, icon: Settings, label: 'Settings' },
          ].map((item) => (
             <button 
                key={item.id}
                onClick={() => setView(item.id)}
                className={`w-full flex items-center gap-3 px-4 py-3.5 rounded-xl transition-all duration-300 group ${
                    view === item.id 
                    ? 'bg-primary/20 text-white border border-primary/20 shadow-[0_0_20px_rgba(99,102,241,0.3)]' 
                    : 'text-slate-400 hover:text-white hover:bg-white/5'
                }`}
            >
                <item.icon size={20} className={view === item.id ? 'text-primary' : 'group-hover:text-white transition-colors'} />
                <span className="font-medium text-sm">{item.label}</span>
            </button>
          ))}
        </nav>

        <div className="p-4 space-y-2">
          <button 
            onClick={handleCheckAndNotify}
            disabled={notificationStatus === 'sending'}
            className="w-full glass-card hover:bg-primary/20 border-white/10 text-white py-3 rounded-xl flex items-center justify-center gap-2 transition-all active:scale-95 group"
          >
            <Send size={16} className={`group-hover:translate-x-1 transition-transform ${notificationStatus === 'sending' ? 'animate-pulse' : ''}`} />
            <span className="text-sm font-medium">Scan & Notify</span>
          </button>

          <button 
            onClick={logout}
            className="w-full bg-red-500/10 hover:bg-red-500/20 text-red-400 py-3 rounded-xl flex items-center justify-center gap-2 transition-all active:scale-95 border border-red-500/10"
          >
             <LogOut size={16} />
             <span className="text-sm font-medium">Sign Out</span>
          </button>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 overflow-y-auto h-[calc(100vh-80px)] md:h-screen p-4 md:p-8 z-10 relative scroll-smooth">
        <div className="max-w-6xl mx-auto pb-20 md:pb-0">
          
          {/* Mobile Header (Minimal) */}
          <div className="md:hidden flex justify-between items-center mb-6 pt-2">
             <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-lg bg-gradient-to-tr from-primary to-accent flex items-center justify-center text-white font-bold shadow-lg shadow-purple-500/20">S</div>
                <h1 className="text-xl font-bold text-white">SubManager</h1>
             </div>
             <button onClick={logout} className="p-2 glass-card rounded-full text-red-400 active:scale-90 transition-transform">
                <LogOut size={18} />
             </button>
          </div>

          {/* View Container */}
          <div className="animate-in fade-in zoom-in-95 duration-500">
            {view === ViewState.DASHBOARD && <Dashboard accounts={processedAccounts} clients={clients} stats={stats} />}
            {view === ViewState.CLIENTS && (
                <ClientList 
                    clients={clients} 
                    services={services}
                    onAdd={handleAddClient} 
                    onUpdate={handleUpdateClient} 
                    onDelete={handleDeleteClient}
                    onAddService={handleAddService}
                    onDeleteService={handleDeleteService}
                />
            )}
            {view === ViewState.ACCOUNTS && (
                <AccountList 
                accounts={processedAccounts} 
                clients={clients}
                services={services}
                onUpdateAccount={handleUpdateAccount}
                onDeleteAccount={handleDeleteAccount}
                />
            )}
            {view === ViewState.SMART_ADD && <SmartAdd services={services} onAddAccount={handleAddAccount} />}
            {view === ViewState.SETTINGS && <TelegramSettings config={telegramConfig} onSave={handleSaveTelegram} />}
          </div>
        </div>
      </main>

      {/* Mobile Bottom Navigation */}
      <nav className="md:hidden fixed bottom-0 left-0 right-0 h-20 glass-panel border-t border-white/10 z-50 flex items-center justify-around px-2 pb-2">
         {[
            { id: ViewState.DASHBOARD, icon: LayoutGrid, label: 'Home' },
            { id: ViewState.ACCOUNTS, icon: List, label: 'Accounts' },
            { id: ViewState.SMART_ADD, icon: PlusCircle, label: 'Add', special: true },
            { id: ViewState.CLIENTS, icon: Users, label: 'Clients' },
            { id: ViewState.SETTINGS, icon: Settings, label: 'Settings' },
          ].map((item) => (
             item.special ? (
                <button 
                    key={item.id}
                    onClick={() => setView(item.id)}
                    className="mb-8 p-4 rounded-full bg-gradient-to-tr from-primary to-accent text-white shadow-[0_0_20px_rgba(244,114,182,0.5)] active:scale-95 transition-transform"
                >
                    <PlusCircle size={28} />
                </button>
             ) : (
                <button 
                    key={item.id}
                    onClick={() => setView(item.id)}
                    className={`flex flex-col items-center gap-1 p-2 rounded-xl transition-all ${
                        view === item.id ? 'text-white' : 'text-slate-500'
                    }`}
                >
                    <item.icon size={22} className={view === item.id ? 'text-primary drop-shadow-[0_0_8px_rgba(99,102,241,0.5)]' : ''} />
                    <span className="text-[10px] font-medium">{item.label}</span>
                </button>
             )
          ))}
      </nav>
    </div>
  );
};

export default App;